# Generated by Django 6.1 on 2026-08-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(verbose_name=100)),
                ('description', models.TextField()),
                ('category', models.CharField(verbose_name=100)),
                ('technologies', models.TextField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
